# Name : Chandrawanshi Mangesh Shivaji
# Roll Number : 1801cs16
# SSD CS392 Assignment 2
# Typing 'make' will create the executable files.

default:
	gcc initialize.c -o initialize.o
	gcc registration.c -o registration.o
	gcc regenerate_honeyindexsets.c -o regenerate_honeyindexsets.o
	gcc login.c -o login.o
	gcc honeychecker.c -o honeychecker.o